---
title: "EJA-paper"
output: html_document
---

# import libraries
```{r libraries}
library(tableone)
library(RColorBrewer)
library(scales)
library(lessR)
library(xlsx)
library(ggpubr)
library(scales)

# library(ReporteRs)
# library(magrittr)
```
# load all files
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r import and load files}
# survey_data <- read_csv("data/survey_data_no_other.csv")
# survey_data_all_countries <- read_csv("data/survey_data_all_countries.csv")
# survey_fragments <- read_csv("data/survey_fragments.csv")
load("Rfiles.RData")

# change "Country where you work?" to "country" for later BIP and EU membership code
names(survey_data)[12] <- "country"
```
```{r Create STRATIFICATION columns}
survey_data <- survey_data %>% 
    mutate(EU_members = case_when(
        country %in% original_EU_member ~ "Original",
        country %in% intermediate_EU_member ~ "Intermediate",
        country %in% post_mill_eu_member ~ "Postmillenial",
        TRUE ~ "NO MEMBER")) 

# first GDP column creation, replaced by GDP per capita for better comparison of countries to minimize the effect of country size on GDP
survey_data <- survey_data %>% 
    mutate(GDP = case_when(
        country %in% high_gdp_countries ~ "High GDP",
        country %in% middle_gdp_countries ~ "Middle GDP",
        country %in% low_gdp_countries ~ "Low GDP")) 

# GDP per capita columen creation for later stratification
survey_data <- survey_data %>% 
    mutate(GDP_PER_CAPITA = case_when(
        country %in% GDP_PC_high ~ "High_GDP_PC",
        country %in% GDP_PC_middle ~ "Middle_GDP_PC",
        country %in% GPD_PC_low ~ "Low_GDP_PC")) 

# GDP per capita columen creation for later stratification
survey_data <- survey_data %>% 
    mutate(dichte = case_when(
        country %in% dichte_high ~ "Hohe_Dichte",
        country %in% dichte_middle ~ "Mittler_Dichte",
        country %in% dichte_low ~ "Geringe_Dichte"))

survey_data <- survey_data %>% 
    mutate(digital_index = case_when(
        country %in% high_digital ~ "High_Digital",
        country %in% middle_digital ~ "Middle_Digital",
        country %in% low_digital ~ "Low_Digital",
        TRUE ~ "NO INDEX"))
```
# links and different
```{r links}
# chi-square calculator
# https://www.socscistatistics.com/tests/chisquare2/default2.aspx
# Digital Health Index
# https://de.statista.com/statistik/daten/studie/1070546/umfrage/stand-der-digitalisierung-des-gesundheitssystems-nach-ausgewaehlten-laendern/
```
```{r creating fct_lump styple chunks}
# https://tradingeconomics.com/country-list/gdp?continent=europe
BIP_DF <- BIP_DF %>% 
    mutate(levels_bip = cut(BIP_DF$BIP, 
                            breaks = c(1, 100, 500, Inf), 
                            labels = c("Low", "Middle", "High")))
```


```{r Table One FIRST PUBLICATION}
# https://cran.r-project.org/web/packages/table1/vignettes/table1-examples.html
# stratification by gender
catVars = "Gender"

contVars = c(
    "Profession",
    "Your expert level"
)
# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateTableOne(
        data = survey_data,
        vars = contVars,
        # testExact = fisher.test,     
        addOverall = FALSE,
        strata = catVars
    )


results_tbl <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)
summary(tableOne)
# writing the table to excel
# write.xlsx(results_tbl,
#            file = "~/Desktop/R/Shiny/ESAIC-survey/ESAIC-KAI-survey-2021/master_data.xlsx",
#            sheetName = "demographics_paper_gender_fix", 
#            col.names = TRUE, 
#            row.names = TRUE, 
#            append = TRUE)
```
```{r Table One Stratified EU member}
# https://cran.r-project.org/web/packages/table1/vignettes/table1-examples.html
# stratification by gender

catVars = "EU_members"

contVars =  questions_table_one_EJA_paper

# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateTableOne(
        data = survey_data,
        vars = contVars,
        testExact = fisher.test,     
        addOverall = FALSE,
        strata = catVars
    )


results_tbl <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)

# writing the table to excel
write.xlsx(results_tbl,
           file = "~/Desktop/R/EJA-ESAIC-survey/tbl_one.xlsx",
           sheetName = "table_one_EU_countries",
           col.names = TRUE,
           row.names = TRUE)
```
```{r Table One GDP Stratified}
# https://cran.r-project.org/web/packages/table1/vignettes/table1-examples.html
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4966396/
# https://www.socscistatistics.com/tests/chisquare2/default2.aspx
# https://www.youtube.com/watch?v=f53nXHoMXx4&t=42s&ab_channel=VectorsAcademy

# stratification by GDP
catVars = "GDP"

contVars = questions_table_one_EJA_paper

survey_data <- survey_data %>% 
    dplyr::filter(GDP != "NO MEMBER")

# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateCatTable(
        data = survey_data,
        vars = contVars,
        # testExact = fisher.test,     
        addOverall = FALSE,
        strata = catVars
    )


results_tbl <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)

# writing the table to excel
write.xlsx(results_tbl,
           file = "~/Desktop/R/EJA-ESAIC-survey/tbl_one_test.xlsx",
           sheetName = "GDP stratified two",
           col.names = TRUE,
           row.names = TRUE)
```
```{r Table One stratified GDP PER CAPITA }
# https://data.worldbank.org/indicator/ny.gdp.pcap.cd
# in US dollar
# stratification by GDP
catVars = "GDP_PER_CAPITA"

contVars = questions_table_one_EJA_paper

# survey_data <- survey_data %>% 
#     select(questions_table_one_EJA_paper) %>% 
#     dplyr::filter(GDP_PER_CAPITA != "NO MEMBER") %>% 
#     dplyr::filter(GDP_PER_CAPITA != "Different (please comment)")

# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateCatTable(
        data = survey_data,
        vars = contVars,
        # testExact = fisher.test,     
        addOverall = FALSE,
        strata = catVars
    )

results_tbl_gdp_pc <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)

# writing the table to excel
write.xlsx(results_tbl_gdp_pc,
           file = "~/Desktop/R/EJA-ESAIC-survey/tbl_one.xlsx",
           sheetName = "GDP_PER_CAP",
           col.names = TRUE,
           row.names = TRUE)
```
```{r Table One stritified DICHTE}
catVars = "dichte"

contVars = questions_table_one_EJA_paper

# survey_data <- survey_data %>% 
#     select(questions_table_one_EJA_paper) %>% 
#     dplyr::filter(GDP_PER_CAPITA != "NO MEMBER") %>% 
#     dplyr::filter(GDP_PER_CAPITA != "Different (please comment)")

# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateCatTable(
        data = survey_data,
        vars = contVars,
        # testExact = fisher.test,     
        addOverall = FALSE,
        strata = catVars
    )

results_tbl_gdp_pc <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)

# writing the table to excel
write.xlsx(results_tbl_gdp_pc,
           file = "~/Desktop/R/EJA-ESAIC-survey/tbl_one_dichte.xlsx",
           sheetName = "dichte",
           col.names = TRUE,
           row.names = TRUE)
```
```{r Table One stritified DIGITAL INDEX}
catVars = "digital_index"

contVars = questions_table_one_EJA_paper

# survey_data <- survey_data %>% 
#     select(questions_table_one_EJA_paper) %>% 
#     dplyr::filter(GDP_PER_CAPITA != "NO MEMBER") %>% 
#     dplyr::filter(GDP_PER_CAPITA != "Different (please comment)")

# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateCatTable(
        data = survey_data,
        vars = contVars,
        # testExact = fisher.test,     
        addOverall = FALSE,
        strata = catVars
    )

results_tbl_gdp_pc <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)

# writing the table to excel
write.xlsx(results_tbl_gdp_pc,
           file = "~/Desktop/R/EJA-ESAIC-survey/digital_index.xlsx",
           sheetName = "dichte",
           col.names = TRUE,
           row.names = TRUE)
```


# Results

```{r Figure 1 technical question aranged by telefone and internet}

# absolute counts
table(survey_data$"Is it possible to obtain informed consent online via internet, in your routine setting?")
# proportions to store in "internet" df and use it for the graph
prop.table(table(survey_data$"Is it possible to obtain informed consent online via internet, in your routine setting?"))

# pie graph for internet 
internet <- data.frame(answer = c("Depends", "Yes", "No"),
                        when_simple = round(c(0.06647399, 0.23121387, 0.70231214), 3) * 100)

# "#a1dab4", "#41b6c4", "#2c7fb8", "#253494" 2 (Claudia bestätigt)
# scale_fill_manual(values=c("#a1dab4", "#41b6c4", "#2c7fb8", "#253494"))
internet_pie <- internet %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 8, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    # scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C"))
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C"))



# pie graph creation for telefone proportions
table(survey_data$"Is it possible to obtain informed consent online via telefone, in your routine setting?")
# proportions to store in "internet" df and use it for the graph
prop.table(table(survey_data$"Is it possible to obtain informed consent online via telefone, in your routine setting?"))


# 24 h prior and 24 prior because of daily routine pooled together
telefone <- data.frame(answer = c("Depends", "Yes", "No"),
                        when_simple = round(c(0.06086957, 0.37246377, 0.56666667), 3) * 100)

# "#a1dab4", "#41b6c4", "#2c7fb8", "#253494" 2 (Claudia bestätigt)
# scale_fill_manual(values=c("#a1dab4", "#41b6c4", "#2c7fb8", "#253494"))
telefone_pie <- telefone %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 8, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    # scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C"))
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C"))

ggarrange(internet_pie, 
          telefone_pie, 
          labels = c("A:  Internet", 
                     "B:  Telefone"),
          font.label = list(size = 19),
          hjust = -0.02,
          ncol = 2)
```

```{r responce counts for different countries}
survey_fragments %>% 
    dplyr::filter(country != "Other") %>% 
    count(country) %>% 
    arrange(desc(n)) %>% 
    print(n = 100)
```
```{r Who obtaines consent?}
survey_fragments %>% 
    count(who.obtains) %>% 
    dplyr::filter(!is.na(who.obtains)) %>% 
    mutate(who.obtains = fct_reorder(who.obtains, n)) %>% 
    ggplot(aes(x = who.obtains, y = n, fill = who.obtains)) +
            geom_col() +
            labs(x = "", 
                 y = "", 
                 title = "Who in general obtains the informed consent?") +
            theme_light(base_size = 15) + 
            theme(title = element_text(size = 25, colour = 'black'),
                  axis.text.x = element_text(size = 22, vjust = 1.3),
                  axis.text.y = element_text(size = 20)) +
            theme(legend.position = "None") +
            scale_fill_brewer(palette = "Set2") +
    coord_flip()
```
```{r data provided by Profession}
table(survey_data$Profession)
prop.table(table(survey_data$Profession))
```
```{r risc scores}
survey_fragments %>% 
    select(ASA.Class:POSPOM) %>% 
    # using dplyrs across function to perform columnwise operations on character data
    summarise(across(is.character, table)) %>% 
    .[2,] %>% 
    gather(risk_score, value) %>% 
    mutate(risc_proportion = value/nrow(survey_fragments)) %>% 
    mutate(risk_score = fct_reorder(risk_score, risc_proportion)) %>% 
    ggplot(aes(x = risk_score, y = risc_proportion, fill = risk_score)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C", "#EFC000FF", "#868686FF")) + 
    labs(x = "", 
                 y = "", 
                 title = "Risk scores used") +
            theme_light(base_size = 15) + 
            theme(title = element_text(size = 25, colour = 'black'),
                  axis.text.x = element_text(size = 22, vjust = 1.3),
                  axis.text.y = element_text(size = 20)) +
            theme(legend.position = "None") +
    coord_flip()
```
```{r questionnaire table}
catVars = "Gender"

contVars = c(
    "Profession",
    "Your expert level"
)
# cava NA's for stratification is not possible since NA is dropped
tableOne <-
    CreateTableOne(
        data = survey_data,
        vars = contVars,
        testExact = fisher.test,     
        addOverall = FALSE,
        strata = catVars
    )


results_tbl <- print(tableOne, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = FALSE, printToggle = FALSE)
summary(tableOne)

```
```{r PIE When do you need to obtain Informed consent for elective surgery based on legal requirements?}
prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for simple procedures, low risk patients)."))
prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for complex procedures, higher risk patients)."))

# 24 h prior and 24 prior because of daily routine pooled together
simple_df <- data.frame(simple_complex = c(rep("simple procedures", 3), rep("complex procedures", 3)),
                        answer = rep(c("2 days or more", "24h or less", "Same day"), 2),
                        when_simple = round(c(0.1289111, 0.5419274, 0.3291615, 0.33625, 0.51625, 0.14750), digits = 3) * 100)


# "#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"
simple_df %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C")) + 
    facet_wrap(~factor(simple_complex, levels = c("simple procedures", "complex procedures")))



################## base R pie ####################################
# when_obtain_simple_complex <- c("2 days or more",
#                         "24h or less",
#                         "Same day")
# 
# when_simple <- round(c(0.1289111, 0.5419274, 0.3291615), digits = 2) * 100
# when_complex <- round(c(0.33625, 0.51625, 0.14750), digits = 2) * 100
# 
# cols = brewer.pal(n = length(when_obtain_simple_complex), name = 'Set1')
# par(mfrow = c(1, 2))
# 
# # prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for simple procedures, low risk patients)."))
# pie(when_simple, 
#     labels = paste0(when_simple, "%"),
#     clockwise = TRUE,
#     col = cols,
#     cex.main=3, 
#     cex = 2.5,
#     main = "simple procedures",
#     radius = 1.2,
#     border = "white")
# 
# legend("bottom", 
#        legend = when_obtain_simple_complex,
#        fill = cols,
#        cex = 1.5, 
#        bty = "n",
#        border = "white",
#        inset = -.06)
# 
# # prop.table(table(survey_data$"When do you need to obtain Informed consent for elective surgery based on legal requirements (for complex procedures, higher risk patients)."))
# pie(when_complex,
#     labels = paste0(when_complex, "%"),
#     clockwise = TRUE,
#     cex.main=3, 
#     cex = 2.5,
#     col = cols,
#     main = "complex procedures",
#     radius = 1.2,
#     border = "white")
```
```{r PIE Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? }
prop.table(table(survey_data$"Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for simple procedures, low risk patients)"))
table(survey_data$"Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for simple procedures, low risk patients)")

prop.table(table(survey_data$"Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for complex procedures, higher risk patients)"))
table(survey_data$"Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for complex procedures, higher risk patients)")


consent_legal <- data.frame(simple_complex = c(rep("simple procedures", 3), rep("complex procedures", 3)),
                        answer = rep(c("Unsure", "No", "Yes"), 2),
                        when_simple = round(c(0.3553616, 0.3715711, 0.2730673, 0.3877805, 0.4251870, 0.1870324), digits = 3) * 100)


consent_legal %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    # "#B2172B", "#08598D", "#1E9D77", "#A7771C" (original)
    # "#ffffb2", "#fecc5c", "#fd8d3c", "#e31a1c" (black and white compatible)
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C")) +
    facet_wrap(~factor(simple_complex, levels = c("simple procedures", "complex procedures")))
```
```{r Thinking of Re-Do / repeated anaesthesia assuming the patient is well informed. Would an online/telephone informed consent then be allowed for elective surgery due to legal requirements in your country?}

prop.table(table(survey_data$`Thinking of Re-Do / repeated anaesthesia assuming the patient is well informed. Would an online/telephone informed consent then be allowed for elective surgery due to legal requirements in your country?`))

redo_legal <- data.frame(answer = c("Unsure", "No", "Yes"),
                        when_simple = round(c(0.3496241, 0.3283208, 0.3220551), digits = 3) * 100)


redo_legal %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    # "#B2172B", "#08598D", "#1E9D77", "#A7771C" (original)
    # "#ffffb2", "#fecc5c", "#fd8d3c", "#e31a1c" (black and white compatible)
    scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C"))
```
```{r Is there a special regulation in your country during this pandemic situation favouring online or telephone informed consent?}
prop.table(table(survey_data$"Is there a special regulation in your country during this pandemic situation favouring online or telephone informed consent?"))
table(survey_data$"Is there a special regulation in your country during this pandemic situation favouring online or telephone informed consent?")

regulations <- data.frame(answer = c("Unsure", "No", "Yes"),
                          when_simple = round(c(0.2518703, 0.5610973, 0.1870324), digits = 3) * 100)


# "#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"
regulations %>% 
    ggplot(aes(x="", y=when_simple, fill=answer)) +
    geom_bar(stat="identity", width=1, color = "white") +
    coord_polar("y", start=0) + 
    theme_void() + 
    geom_text(aes(label = paste0(when_simple, "%")),
              size = 10, 
              colour="white",
              position = position_stack(vjust = 0.5)) +
    theme(legend.position="bottom",
          legend.title = element_blank(),
          legend.text = element_text(size=30),
          legend.spacing.x = unit(1.5, 'cm'),
          strip.text.x = element_text(size=35)) +
    # "#00441B", "#053060", "#660A1F", "#A7771C" (Dunkel)
    # "#4B72AF", "#54A968", "#C64E51", "#DCAD94" (etwas weniger knallig)
    # scale_fill_manual(values=c("#B2172B", "#08598D", "#1E9D77", "#A7771C"))
    scale_fill_manual(values=c("#a1dab4", "#41b6c4", "#2c7fb8", "#253494"))

# pandemic_adjustments_values = round(c(0.2518703, 0.5610973, 0.1870324), 2) * 100
# 
# pie(pandemic_adjustments_values, 
#     labels = paste0(pandemic_adjustments_values, "%"),
#     clockwise = TRUE,
#     col = cols,
#     cex.main=3, 
#     cex = 2.5,
#     radius = 0.8,
#     border = "white")
# 
# 
# legend("bottom", 
#        legend = pandemic_adnustments,
#        fill = cols,
#        cex = 1.5, 
#        bty = "n",
#        border = "white",
#        horiz = TRUE,
#        y = 2)


```

```{r R files used for analysis}
# this will save all objects to REata for later load
save(
    "all_questions",
    "all_questions_list",
    "BIP_DF",
    "high_gdp_countries",
    "intermediate_EU_member",
    "low_gdp_countries",
    "middle_gdp_countries",
    "original_EU_member",
    "post_mill_eu_member",
    "questions_table_one_EJA_paper",
    "survey_data",
    "survey_data_all_countries",
    "survey_fragments",
    # master tibble with GDP per capita 
    "GDP_PC",
    # list fo column creation in the master file for later stratification
    "GDP_PC_high",
    "GDP_PC_middle",
    "GPD_PC_low",
    "bevoelkerungsdichte",
    # Bevölkerungsdichte
    "dichte_high",
    "dichte_middle",
    "dichte_low",
    # variables for creating digital_index column
    "high_digital",
    "middle_digital",
    "low_digital",
    file = "Rfiles.RData"
)




# storing all column names as a list of characters
all_questions <- dput(names(survey_data)) 

original_EU_member <- c("Belgium",
              "France",
              "Germany",
              "Italy",
              "Luxemburg",
              "Netherlands")

intermediate_EU_member <- c("Austria",
                     "Denmark",
                     "Finland",
                     "Greece",
                     "Ireland",
                     "Portugal",
                     "Spain",
                     "Sweden")

post_mill_eu_member <- c("Bulgaria",
                  "Croatia",
                  "Cyprus",
                  "Czechia",
                  "Estonia",
                  "Hungary",
                  "Latvia",
                  "Lithuania",
                  "Malta",
                  "Poland",
                  "Romania",
                  "Slovakia",
                  "Slovenia")

# lists for GPD per capita and column creation in the masterfile (survey_data) for statification
# assignment just with 15 countries per block after descending arrangement 
GDP_PC_high <-
    c(
        "Liechtenstein",
        "Luxembourg",
        "Switzerland",
        "Ireland",
        "Norway",
        "Denmark",
        "Iceland",
        "Netherlands",
        "Sweden",
        "Finland",
        "Austria",
        "Germany",
        "Belgium",
        "Israel",
        "United Kingdom (UK)"
    )

GDP_PC_middle <- c(
    "France",
    "Italy",
    "Malta",
    "Cyprus",
    "Spain",
    "Slovenia",
    "Estonia",
    "Czechia",
    "Portugal",
    "Lithuania",
    "Slovakia",
    "Latvia",
    "Greece",
    "Hungary",
    "Poland"
)


GPD_PC_low <- c(
    "Croatia",
    "Romania",
    "Russia",
    "Bulgaria",
    "Kazakhstan",
    "Turkey",
    "Serbia",
    "Montenegro",
    "Belarus",
    "Bosnia and Herzegovina",
    "North Macedonia (formerly Macedonia)",
    "Albania",
    "Moldova",
    "Kosovo",
    "Ukraine",
    "Uzbekistan"
)

# old files for stratification, but not used anymore because GDP per capita is more correct
high_gdp_countries <- c(
    "Germany",
    "United Kingdom (UK)",
    "France",
    "Italy",
    "Russia",
    "Spain",
    "Netherlands",
    "Switzerland",
    "Turkey",
    "Poland",
    "Sweden",
    "Belgium"
)

middle_gdp_countries <- c(
    "Austria",
    "Ireland",
    "Norway",
    "Denmark",
    "Finland",
    "Romania",
    "Czechia",
    "Portugal",
    "Greece",
    "Ukraine",
    "Hungary",
    "Slovakia",
    "Israel",
    "Kazakhstan"
)

low_gdp_countries <- c(
    "Luxembourg",
    "Bulgaria",
    "Belarus",
    "Croatia",
    "Lithuania",
    "Slovenia",
    "Serbia",
    "Latvia",
    "Estonia",
    "Cyprus",
    "Iceland",
    "Bosnia and Herzegovina",
    "Albania",
    "Malta",
    "North Macedonia (formerly Macedonia)",
    "Moldova",
    "Monaco",
    "Kosovo",
    "Georgia",
    "Liechtenstein",
    "Uzbekistan"
)

# Bevölkerungsdichte assignment in 3 groups with highest, middle and lowest 15 countries
dichte_high <-
    c(
        "Malta",
        "Netherlands",
        "Israel",
        "Belgium",
        "United Kingdom (UK)",
        "Germany",
        "Liechtenstein",
        "Luxembourg",
        "Switzerland",
        "Italy",
        "Kosovo",
        "Czechia",
        "Denmark",
        "Cyprus",
        "Poland"
    )

dichte_middle <- c(
    "Moldova",
    "France",
    "Portugal",
    "Slovakia",
    "Hungary",
    "Albania",
    "Austria",
    "Slovenia",
    "Turkey",
    "Serbia",
    "Spain",
    "Greece",
    "Romania",
    "North Macedonia (formerly Macedonia)",
    "Ukraine"
)

dichte_low <- c(
    "Croatia",
    "Uzbekistan",
    "Bosnia and Herzegovina",
    "Ireland",
    "Bulgaria",
    "Lithuania",
    "Belarus",
    "Montenegro",
    "Latvia",
    "Estonia",
    "Sweden",
    "Finland",
    "Norway",
    "Russia",
    "Kazakhstan",
    "Iceland"
)

# GDP tibble, not used for publication because GDP per capita is a better marker for comparison of country aconomy
BIP_DF <- tibble(
    country = c(
        "Germany",
        "United Kingdom (UK)",
        "France",
        "Italy",
        "Russia",
        "Spain",
        "Netherlands",
        "Switzerland",
        "Turkey",
        "Poland",
        "Sweden",
        "Belgium",
        "Austria",
        "Ireland",
        "Norway",
        "Denmark",
        "Finland",
        "Romania",
        "Czechia",
        "Portugal",
        "Greece",
        "Ukraine",
        "Hungary",
        "Slovakia",
        "Luxembourg",
        "Bulgaria",
        "Belarus",
        "Croatia",
        "Lithuania",
        "Slovenia",
        "Serbia",
        "Latvia",
        "Estonia",
        "Cyprus",
        "Iceland",
        "Bosnia and Herzegovina",
        "Albania",
        "Malta",
        "North Macedonia (formerly Macedonia)",
        "Moldova",
        "Monaco",
        "Kosovo",
        "Georgia",
        "Israel",
        "Kazakhstan",
        "Liechtenstein",
        "Uzbekistan"
    ),
    BIP = c(
        3846,
        2708,
        2630,
        1886,
        1484,
        1281,
        914,
        752,
        720,
        594,
        541,
        515,
        431,
        426,
        363,
        356,
        270,
        249,
        245,
        231,
        189,
        156,
        155,
        105,
        73.26,
        69.11,
        60.26,
        55.97,
        55.89,
        53.59,
        52.96,
        33.51,
        30.65,
        23.8,
        21.71,
        19.79,
        14.8,
        14.65,
        12.27,
        11.91,
        8,
        7.61,
        15.89,
        402,
        169.8,
        6.69,
        57.7
    )
)

# all questions that are used for Table one creation 
questions_table_one_EJA_paper <- c(
    # legal quesions
    "When do you need to obtain Informed consent for elective surgery based on legal requirements (for complex procedures, higher risk patients).",
    "When do you need to obtain Informed consent for elective surgery based on legal requirements (for simple procedures, low risk patients).",
    "Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for complex procedures, higher risk patients)",
    "Is an online/telephone informed consent for elective surgery in accordance with the legal requirements in your country? (for simple procedures, low risk patients)",
    "Do you know if it is legally allowed to obtain informed consent via Internet or telephone (for simple procedures, low risk patients) in your country?",
    "Thinking of Re-Do / repeated anaesthesia assuming the patient is well informed. Would an online/telephone informed consent then be allowed for elective surgery due to legal requirements in your country?",
    # technical questions
    "Is it possible to obtain informed consent online via internet, in your routine setting?",
    "Is it possible to obtain informed consent online via telefone, in your routine setting?",
    # other questions
    "When ensuring a certain guideline, which may include i.e. specific appointment (time and date) for the interview, secure data protected online service, asking if there is a relaxed environment without distraction, parents’ explicit agreement in online or telephone interview. Would this be an alternative to personal face-to-face meetings?",
    "How would you prefer to do the anaesthesiological preoperative evaluation in the future?",
    "Is there a special regulation in your country during this pandemic situation favouring online or telephone informed consent?"
)

# tibble for GDP per capita in USD
#https://data.worldbank.org/indicator/ny.gdp.pcap.cd
GDP_PC <- tibble(
    countries =
        c(
            "Luxembourg",
            "Ireland",
            "Switzerland",
            "Norway",
            "Denmark",
            "Netherlands",
            "Iceland",
            "Austria",
            "Germany",
            "Sweden",
            
            "Belgium",
            "Finland",
            "France",
            "United Kingdom (UK)",
            "Malta",
            
            "Italy",
            "Czechia",
            "Cyprus",
            "Lithuania",
            "Slovenia",
            
            "Spain",
            "Estonia",
            "Poland",
            "Portugal",
            "Hungary",
            
            "Slovakia",
            "Latvia",
            "Romania",
            "Turkey",
            "Greece",
            
            "Croatia",
            "Russia",
            "Bulgaria",
            "Belarus",
            "Montenegro",
            
            "Serbia",
            "North Macedonia (formerly Macedonia)",
            "Bosnia and Herzegovina",
            "Albania",
            "Ukraine",
            
            "Moldova",
            "Kosovo",
            "Israel",
            "Kazakhstan",
            "Liechtenstein",
            "Uzbekistan"),
    GDP_PC = c(
        116014.6,
        85267.8,
        87097.0,
        67329.7,
        61063.3,
        52397.1,
        59270.2,
        48586.8,
        46208.4,
        52274.4,
        45159.3,
        48745.0,
        39030.4,
        41059.2,
        27884.6,
        31714.2,
        22931.3,
        27527.8,
        20233.6,
        25517.3,
        27063.2,
        23027.0,
        15721.0,
        22176.3,
        15980.7,
        19266.5,
        17726.3,
        12896.1,
        8536.4,
        17622.5,
        14134.2,
        10126.7,
        10079.2,
        6424.2,
        7677.2,
        7720.5,
        5917.3,
        6079.7,
        5246.3,
        3724.9,
        4547.1,
        4346.6,
        44168.9,
        9122.2,
        175813.9,
        1750.7
    )
)


# Bevölkerungsdichte Einwohner je km
bevoelkerungsdichte <- tibble(
    countries =
        c(
            "Luxembourg",
            "Ireland",
            "Switzerland",
            "Norway",
            "Denmark",
            "Netherlands",
            "Iceland",
            "Austria",
            "Germany",
            "Sweden",
            "Belgium",
            "Finland",
            "France",
            "United Kingdom (UK)",
            "Malta",
            "Italy",
            "Czechia",
            "Cyprus",
            "Lithuania",
            "Slovenia",
            "Spain",
            "Estonia",
            "Poland",
            "Portugal",
            "Hungary",
            "Slovakia",
            "Latvia",
            "Romania",
            "Turkey",
            "Greece",
            "Croatia",
            "Russia",
            "Bulgaria",
            "Belarus",
            "Montenegro",
            "Serbia",
            "North Macedonia (formerly Macedonia)",
            "Bosnia and Herzegovina",
            "Albania",
            "Ukraine",
            "Moldova",
            "Kosovo",
            "Israel",
            "Kazakhstan",
            "Liechtenstein",
            "Uzbekistan"),
    dichte = c(
        218.8,
        68.2,
        210.5,
        14.2,
        134.1,
        502.3,
        3.3,
        105.3,
        234.4,
        23.8,
        372.8,
        18,
        117.7,
        270.3,
        1336.3,
        202.3,
        137.3,
        125.6,
        46.8,
        103,
        93,
        31,
        125,
        113.8,
        108.1,
        113.1,
        32,
        86.4,
        101.7,
        87,
        75.7,
        8.8,
        66.1,
        46.7,
        46.7,
        101.2,
        82.4,
        69.3,
        106.7,
        77.1,
        123.8,
        164.2,
        373.2,
        7,
        233.8,
        74
    )
)

# list to create a digital health index
# https://de.statista.com/statistik/daten/studie/1070546/umfrage/stand-der-digitalisierung-des-gesundheitssystems-nach-ausgewaehlten-laendern/
digital_health_index <- c(
    country = c(
        "Estonia",
        "Denmark",
        "Israel",
        "Spain",
        "United Kingdom (UK)",
        "Schweden",
        "Portugal",
        "Netherlands",
        "Austria",
        "Italy",
        "Belgium",
        "Switzerland",
        "France",
        "Germany",
        "Poland"
    ),
    index = c(
        81.9,
        72.5,
        72.4,
        71.4,
        70,
        68.3,
        67.2,
        66.1,
        59.8,
        55.8,
        54.7,
        40.6,
        31.6,
        30,
        28.5
    )
)
    
high_digital <- c("Estonia",
                  "Denmark",
                  "Israel",
                  "Spain",
                  "United Kingdom (UK)")

middle_digital <- c("Schweden",
                    "Portugal",
                    "Netherlands",
                    "Austria",
                    "Italy")

low_digital <- c("Belgium",
                 "Switzerland",
                 "France",
                 "Germany",
                 "Poland")

    
    
    

# survey_data_barchart$country[survey_data_barchart$country == "United Kingdom (UK)"] <- "UK" 
# survey_data_barchart$country[survey_data_barchart$country == "North Macedonia (formerly Macedonia)"] <- "Macedonia" 
# survey_data_barchart$country[survey_data_barchart$country == "Bosnia and Herzegovina"] <- "B&H" 
```
